### ISSUE TITLE
CI tests pass even when some test cases fail

### ISSUE THREAD

**Issue by Zodiase** [Zodiase/map-visualizer#23]
See the raw log:

```
33.26s$ npm test
> map-visualizer@1.0.0 test /home/travis/build/Zodiase/map-visualizer
> bash test/start.sh
Waiting for servers to start....Done
Running tests with WebDriver...
․․․․․․FF․F․․․․․․․․․․․․․․․
22 passing (29.50s)
3 failing
1) url should notify when no source file url included:
expected 'N' to equal '#source='
running phantomjs
AssertionError: expected 'N' to equal '#source='
    at Object.<anonymous> (/home/travis/build/Zodiase/map-visualizer/test/wdio.conf.js:154:33)
    at /home/travis/build/Zodiase/map-visualizer/node_modules/wdio-mocha-framework/node_modules/wdio-sync/build/index.js:311:29
2) url should notifying user when no source url available:
expected 'N' to equal ''
running phantomjs
AssertionError: expected 'N' to equal ''
    at Object.<anonymous> (/home/travis/build/Zodiase/map-visualizer/test/wdio.conf.js:154:33)
    at /home/travis/build/Zodiase/map-visualizer/node_modules/wdio-mocha-framework/node_modules/wdio-sync/build/index.js:311:29
3) file data should catch error when invalid json file format included:
expected 'Downloading source file...' to equal '#source=https://raw.githubusercontent.com/Zodiase/map-visualizer/gh-pages/sample-source/invalid-json.json'
running phantomjs
AssertionError: expected 'Downloading source file...' to equal '#source=https://raw.githubusercontent.com/Zodiase/map-visualizer/gh-pages/sample-source/invalid-json.json'
    at Object.<anonymous> (/home/travis/build/Zodiase/map-visualizer/test/wdio.conf.js:154:33)
    at /home/travis/build/Zodiase/map-visualizer/node_modules/wdio-mocha-framework/node_modules/wdio-sync/build/index.js:311:29
Killing background processes...Done
The command "npm test" exited with 0.
Done. Your build exited with 0.
```

The CI script needs fixing.

**Comment by Zodiase** [comment]
Fixed by a341e1fc06b74bd03c30e483955160b288a208d8
